### PR TITLE
80 x m17

### PR DESCRIPTION
**Pull request by vischia**
Producing FTs needed for taus.

It turns out that some of the modifications I made to @peruzzim repository following Giovanni's requests are still listed in the diff, so I guess that they were forgotten at the moment of the big merge, so this is a good moment to merge them now.

Best,
Pietro

### CODE REVIEW

**Comment by cheidegg** [comment]
I have two comments:
(1) I see two different directories in susy-interface/cmds: tauEWK and tau-ewkino. They seem to contain similar files. Can you please tidy this up? 
(2) It seems you are using susy-interface category 3l for your tau studies. Can you please make a new configuration as I think we should keep the „3l“ config the default for the analysis, i.e. ready for running limits and plots

**Comment by vischia** [comment]
HI Constantin, 

1) yes that's because you had renamed the "cmds/pietro" to tauEWK while I had named it tau-ewkino. I removed today the last vestige of the "tauEWK" one, so in the final result there will be only the tau-ewkino.

2) Do you mean a separate section in the env/configs? Sure. What about "taustudies"?

Best,
Pietro

**Comment by cheidegg** [comment]
(1) I see. Ok, yes, please remove it.
(2) Whatever you like. 
Thanks!

**Comment by vischia** [comment]
Hi,

both points 1 and 2 are taken care of now, with the latest 2 commits.

I have to auth for merging PRs, so I cannot do it myself.

Best,
Pietro

**Pull request merged**
